FROM williamyeh/ansible:centos7
USER root

RUN yum -y install git

RUN pip install --upgrade pip
RUN pip install requests

RUN mkdir /home/devnet
WORKDIR /home/devnet

ENTRYPOINT ["ansible-playbook", "site.yml"]

